# Generated by Django 5.1.7 on 2025-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sequence_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'counters',
            },
        ),
    ]
