# Generated by Django 5.1.7 on 2025-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_studentrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='department',
            field=models.IntegerField(),
        ),
    ]
