# Generated by Django 5.1.7 on 2025-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studentrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='importance',
            field=models.CharField(max_length=255),
        ),
    ]
