# Generated by Django 5.1.7 on 2025-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_studentrequest_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
