# Generated by Django 5.1.7 on 2025-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('idr', models.AutoField(primary_key=True, serialize=False)),
                ('id_sending', models.IntegerField()),
                ('id_receiving', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('documents', models.JSONField(default=list)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
