# Generated by Django 5.1.7 on 2025-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='department',
            field=models.IntegerField(max_length=255),
        ),
    ]
