# Generated by Django 5.1.7 on 2025-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studentrequest_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='documents',
            field=models.FileField(upload_to=''),
        ),
    ]
